### PR TITLE
Implement example core

### PR DESCRIPTION
**Pull request by Lattay**
Hello,
So I am very interested in using this lib for personal projects and I figured I would give a hand with examples for a starter.
So this WIP PR is for implementing "all" *core* examples from the raylib website.
I am not so sure about the relevance of some cases (like core_basic_window_web and core_vr_simulator).

- [x] core_2d_camera
- [x] core_basic_window
- [x] core_input_keys
- [x] core_input_mouse
- [x] core_input_mouse_wheel
- [x] core_2d_camera_platformer
- [x] core_3d_camera_first_person
- [x] core_3d_camera_free
- [x] core_3d_camera_mode
- [x] core_drop_files
- [x] core_vr_simulator
- [x] core_random_values
- [x] core_loading_thread
- [x] core_3d_picking
- [x] core_window_letterbox
- [x] core_storage_values
- [ ] core_input_gamepad
- [ ] core_quat_conversion
- [ ] core_scissor_test
- [ ] core_world_screen

EDIT:
Definitly not doable or probably not doable for now:
- core_basic_window_web
- core_custom_logging
- core_input_gestures
- core_input_multitouch

### CODE REVIEW

**Comment by tjammer** [comment]
Thank you very much for this!

I am also not sure about the basic_window_web example. AFAIK there is no wasm-target for OCaml yet, and I don't know if it's possible to use jsoo for something like this. But it would certainly be nice to have something like this in the future.

The VR  example also won't be doable right now, b/c the set_vr_configuration function is missing from the bindings, but it should be possible to add it. I have a look later today.

**Comment by Lattay** [comment]
Indeed I don't think it would be easy to produce a jsoo/emscripten raylib target, definitely out of my scope right now.
I will be focusing on example for mainstream targets in this PR.

**Comment by tjammer** [comment]
Regarding core custom logging: I haven't been able to bind the callback function with the va_list argument, so we will have to put the example in the lower category unfortunately.

However, the core_vr_simulator example does work, since it only seems to simulate VR (I don't have a VR headset to test otherwise, but the example at least behaves like the C one does).

**Comment by Lattay** [comment]
No problem,
I fixed the conflict and updated the todo list, thank you :+1:

**Comment by Lattay** [comment]
To prevent more conflict I propose that the dune file is kept sorted in alphabetic order of the name fields.
Here is a quick and dirty script to help do that: https://gist.github.com/Lattay/72e0f90411cb70139fac419da6cd2118

**Comment by Lattay** [comment]
Hey,
I am kind of bored with this and don't have much free time to spend en it so I think I won't do the few missing examples.
Consider merging this now.
good luck

**Comment by tjammer** [comment]
Thank you very much for the contribution :)

**Pull request merged**
